services:
  source:
    build:
      context: .
      dockerfile: ./docker/source.Dockerfile
    pull_policy: build
    restart: on-failure
    ports:
      - 13372:13372

  level1:
    build:
      context: .
      dockerfile: ./docker/slides.Dockerfile
    pull_policy: build
    restart: on-failure
    command: ["level1.md"]
    environment:
      - SOURCE_PROTOCOL=http
      - SOURCE_HOST=localhost
      - SOURCE_PORT=13372
      - SLIDE1_HOST=localhost
      - SLIDE1_PORT=13371
      - SLIDE2_HOST=localhost
      - SLIDE2_PORT=13373
    volumes:
      - keys:/keys
    ports:
      - 13371:53531

  level2:
    build:
      context: .
      dockerfile: ./docker/slides.Dockerfile
    pull_policy: build
    restart: on-failure
    command: ["level2.md"]
    environment:
      - SOURCE_PROTOCOL=http
      - SOURCE_HOST=localhost
      - SOURCE_PORT=13372
      - SLIDE1_HOST=localhost
      - SLIDE1_PORT=13371
      - SLIDE2_HOST=localhost
      - SLIDE2_PORT=13373
    volumes:
      - keys:/keys
    ports:
      - 13373:53531

volumes:
  keys:
