services:
  backend:
    build: ./backend
    pull_policy: build
    restart: on-failure
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    pull_policy: build
    restart: on-failure
    ports:
      - "8080:80"
