name: Docker Build and Push

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SHORT_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push slides image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/slides.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/slides:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/slides:${{ env.SHORT_SHA }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/slides:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push source image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/source.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/source:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/source:${{ env.SHORT_SHA }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/source:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
